FORMAT: 1A
HOST : 172.22.21.11:3000

# Going2Campus API documentation

This is the documentation for our car-sharing API, Going2Campus.

# Group Users

## User Collection [/users]

### Get All Users [GET]
+ Response 200 (application/json)
    + Attributes (array[User])

### Get Me [GET /me]
+ Response 200 (application/json)
    + Attributes (User)
    
### Delete User [DELETE /{id}]
+ Parameters
    + id
+ Response 204 (application/json)
    + Attributes (User)
    
+ Response 503 (application/json)
    + Attributes 
        + message  (string)
    + Body

            { "message" : "Could not retrieve the user." }
            
+ Response 404 (application/json)
    + Attributes 
        + message  (string)
    + Body

            { "message" : "User not found." }
        
# Data Structures

## User(object)
- mail: user@ipl.com (string) - The user's e-mail
- name: José Milho (string) - The user's name
- rating: 5 (number) - The user's rating (0-5)
- numberOfRates: 420 (number) - How many rates the user has been given
- preferences: talker, smoker (array[string]) - User's preferences being the driver
- birthDate: `1997-09-08T23:00:00.000Z` (string) - User's date of birth
- cancel_index: 0.1 (number) - How often this user cancels a trip
